### ISSUE TITLE
Errors when compiling with /WX MSVC

### ISSUE THREAD

**Issue by Lumengine** [brenocq/implot3d#4]
First, really nice to have that kind of library , so thank you !
When compiling with MSVC, and the /WX (warnings as errors), there is a lot of  "warning C4244" with double to float issues. Would be nice to not have them! 
(I can find thime to make a PR if it's open)
Thanks

**Comment by brenocq** [comment]
Thank you for testing and taking the time to write the issue! I'm glad to hear it's working on Windows as well — I’ve only tested it on Linux so far. I don't currently have a Windows setup ready to test this, but I plan to set it up in the next few days.

If you have the time for it, I would be more than happy to accept your PR. That would be greatly appreciated! Otherwise, I’ll take a look at this once I have my Windows environment ready.

Thank youuu :)

**Comment by floooh** [comment]
Interestingly, on Gitlab CI the Windows build has actual hard errors (same problem with the `std::` prefix on math functions like on the macOS build) - maybe it depends on the Visual Studio version.

`D:\a\implot3d\implot3d\implot3d.cpp(2680,14): error C2039: 'fabs': is not a member of 'std' `

...e.g. see: https://github.com/floooh/implot3d/actions/runs/12393862255/job/34596016569

(I also provided a PR which adds this Github CI support).

**Comment by Lumengine** [comment]
> Interestingly, on Github CI the Windows build has actual hard errors (same problem with the `std::` prefix on math functions like on the macOS build) - maybe it depends on the Visual Studio version.
> 
> `D:\a\implot3d\implot3d\implot3d.cpp(2680,14): error C2039: 'fabs': is not a member of 'std' `
> 
> ...e.g. see: https://github.com/floooh/implot3d/actions/runs/12393862255/job/34596016569
> 
> ...I also provided a PR which adds this Github CI support - and this `std::` problem might be fixed by the macOS PR I also created, but if you need help with testing and fixing the Windows build I can also have a look (just need to switch laptops).

I'm using Vs2022 v143 FYI. I didn't test the runtime yet. 
I'll try to make a PR asap to fixes the warnings.

**Comment by floooh** [comment]
Cool :) Re those `std::` errors, it's probably better to use the ImGui wrapper functions as mentioned here anyway:

https://github.com/brenocq/implot3d/issues/5#issuecomment-2550958517

**Comment by Lumengine** [comment]
There are also some IMPLOT3D_API missing on both ImPlot3dPoint (ImPlot has just header struct) and ImPlot3DBox

**Comment by Lumengine** [comment]
Runtime is working on windows 
![image](https://github.com/user-attachments/assets/ce70cace-c4b7-4231-9749-84323a95a526)

**Comment by Lumengine** [comment]
> Thank you for testing and taking the time to write the issue! I'm glad to hear it's working on Windows as well — I’ve only tested it on Linux so far. I don't currently have a Windows setup ready to test this, but I plan to set it up in the next few days.
> 
> If you have the time for it, I would be more than happy to accept your PR. That would be greatly appreciated! Otherwise, I’ll take a look at this once I have my Windows environment ready.
> 
> Thank youuu :)

Here is the PR https://github.com/brenocq/implot3d/pull/11

**Comment by brenocq** [comment]
I'm closing this issue since @Lumengine's PR #11 has been merged into `main`. Thank you!!
